### PR TITLE
Typo fixes in preface

### PR DESCRIPTION
**Pull request by erinann**
- Clean up the "Help!" intro line.
- Remove redundant "first" in first bullet below "Help!" intro line.

### CODE REVIEW

**Comment by ismayc** [comment]
Thanks, @erinann! This is perfectly-sized PR. Easy for us to review. I'll let @rudeboybert review before merging.

**Comment by ismayc** [comment]
Given @mcconvil wrote the preface, I'd like to check for her thoughts too.

**Comment by mcconvil** [comment]
@ismayc I am okay with it (since I think the foreword appears separately from the preface).

**Comment by ismayc** [comment]
Derp! I always get them mixed up. Thanks for writing the *Foreword* not the *Preface*, Kelly! 😄  I'll let you go back to your day now... 🥇

**Pull request merged**
