### PR TITLE
Chester red pen edits

### PR DESCRIPTION
**Pull request by ismayc**
@rudeboybert These are mostly just typo fixes. I do have one question on your Chapter 2 commit though. Do we want to be showing `group_by()` and `summarize()` in Chapter 2? I think it's better to omit it and just show the table as I did in a commit in this PR [here](https://github.com/moderndive/ModernDive_book/commit/c8fdca4f700aaae1191253948179d2d9daba1200).

### CODE REVIEW

**Comment by rudeboybert** [comment]
Ah, ok. The issue was we showed code later that used the data frame created with the `group_by()` and `summarize()`:

```
ggplot(data = flights_counted, mapping = aes(x = carrier, y = number)) +
  geom_col()
```
Students in my class then asked me where the data frame `flights_counted` was. Perhaps we should revert my commit, but also remove the above bit of code?

**Comment by ismayc** [comment]
How about we add flights_counted to the moderndive package? That way we can skirt the issue of showing this code?

**Comment by ismayc** [comment]
Or, yes, it is probably easier to just remove the ggplot() code that mentions flights_counted.

**Comment by rudeboybert** [comment]
Yeah, let's do that then. I'll revert after I merge this PR.

**Pull request merged**
