### PR TITLE
Apply {styler} formatting clean / Typos

### PR DESCRIPTION
**Pull request by ismayc**
```
install.packages("styler")
rmds <- list.files(pattern = "+(.Rmd)$")
purrr::walk(rmds, styler::style_file)
```

### CODE REVIEW

**Comment by rudeboybert** [comment]
Also, I think you need to add you github username and email on the command line. your commits are being attributed to a blank octocat icon, instead of you

**Comment by ismayc** [comment]
Good catch! Not sure how it got removed but it's fixed now. I've also added this in to [Release Steps](#57).

**Comment by rudeboybert** [comment]
Based on what I've seen from my students, I think it's when you update your OS.

**Comment by ismayc** [comment]
Ah! Yep. That’s it for me too. Thanks.

**Comment by ismayc** [comment]
Included the #332 typo in this branch as well. Feel free to review and merge and delete that branch.

**Comment by rudeboybert** [comment]
Gonna close this and re-run styler after my edits; fixing the merge conflicts isn't worth it given that styler takes no time to run

**Comment by rudeboybert** [comment]
Nuts, I forgot about your typo fixes

**Pull request merged**
