### PR TITLE
Update

### PR DESCRIPTION
**Pull request by ismayc**

### CODE REVIEW

**Comment by rudeboybert** [comment]
GitHub question for you. Why make this an explicit PR? Why not just fetch the changes from upstream?

**Comment by rudeboybert** [comment]
Is it because, say, if there were several commits associated with this PR, then by bunching them up in the same PR, we can revert all the commits in one shot by reverting the entire PR?

**Comment by ismayc** [comment]
It’s just a simple thing to do in GitHub so I don’t forget to sync them up later which might cause a merge conflict if I go from my branch into master. I’m not sure if an easier way to do that?

**Comment by rudeboybert** [comment]
I currently do this, for no other better reason than it's what I've been doing: [syncing a fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork):

* Create a remote that points to an upstream repo (here `master`)
* Fetch upstream then merge into master

I wonder if de facto they do the same thing. If I ever figure it out, I'll report back

**Pull request merged**
