### PR TITLE
Fix ?? in table references and add PDF build

### PR DESCRIPTION
**Pull request by ismayc**
bookdown builds are included since I couldn't figure out a way to have Travis build a PDF yet

### CODE REVIEW

**Comment by rudeboybert** [comment]
Sorry for delay, will look at this weekend!

**Comment by ismayc** [comment]
@rudeboybert I'd recommend updating all packages on your machine and doing one more build here. You might need to just delete the `bib/packages.bib` file on `master` and then merge this in too to avoid the messy merge conflicts.

**Comment by rudeboybert** [comment]
@ismayc Thoughts on adding `bib/packages.bib` to `.gitignore` for now?

**Comment by ismayc** [comment]
@rudeboybert Makes sense since it is auto-generated I think. We’ll just have to make sure to keep our packages updated I think.

**Comment by rudeboybert** [comment]
Ok, will add that to the "TODO's before launch list"

**Pull request merged**
