### PR TITLE
Update Chester affiliation

### PR DESCRIPTION
**Pull request by ismayc**

### CODE REVIEW

**Review by rudeboybert — APPROVED** [review]

**Comment by ismayc** [comment]
Not sure if we wanna push to moderndive.com too? Happy to wait until the next release if that's better.

**Comment by rudeboybert** [comment]
@ismayc go ahead and push to moderndive.com too!

**Comment by ismayc** [comment]
@rudeboybert I'm forgetting how we do this. (It's been too long...) Manually build of the master branch and then send that to gh-pages? We don't have the automatic build set up for the releases now, right?

**Comment by ismayc** [comment]
Never mind! Just needed to switch over to travis-ci.com instead of travis-ci.org to get the builds to go through for both moderndive.netlify.app and moderndive.com. The `build | passing` button is now working on the README too 😄

**Pull request merged**
