### PR TITLE
Marium ch7-10 + 11 refactoring

### PR DESCRIPTION
**Pull request by mariumtapal**

### CODE REVIEW

**Comment by mariumtapal** [comment]
screenshot 2

@rudeboybert In the screenshot, the development version (for ch9) has two warning messages, one of which we don’t want but the other we do. Currently, the code chunk is set to `warning=TRUE`.

**Comment by rudeboybert** [comment]
@ismayc I think trying to split these two warning messages and suppress the latter one for sake of consistency with the print edition is not going to be worth the effort. thoughts?

**Comment by ismayc** [comment]
@rudeboybert I wonder if this just means that {infer} needs to be updated so that `shade_p_value()` doesn't produce this warning? I like having the other warning in the book to help readers. Can you confirm that `shade_p_value()` produces this and then [file an issue](https://github.com/tidymodels/infer/issues)?

**Comment by rudeboybert** [comment]
Heads up @mariumtapal, I "rebased" your `marium-ch11-refactoring` to be this `marium-ch7-10-refactoring` instead of `master` and merged. this way your two PR's are now merged to this single one.

**Comment by rudeboybert** [comment]
Good call @ismayc it turns out that the difference in warning messages was an `infer` versioning issue.

@mariumtapal It is a good idea to update R and all packages accordingly, just so we’re on the same page with package versions. However, as Chester can attest to I myself forgot to do this yesterday before other work. 

Here is my `sessionInfo()` just in case
``` r
sessionInfo()
#> R version 4.0.1 (2020-06-06)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Catalina 10.15.5
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_4.0.1  magrittr_1.5    tools_4.0.1     htmltools_0.5.0
#>  [5] yaml_2.2.1      stringi_1.4.6   rmarkdown_2.2   highr_0.8      
#>  [9] knitr_1.28      stringr_1.4.0   xfun_0.14       digest_0.6.25  
#> [13] rlang_0.4.6     evaluate_0.14
```

<sup>Created on 2020-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Pull request merged**
